export const userSignUpConstants = {
  USER_SIGN_UP_FAILURE: "USER_SIGN_UP_FAILURE",
  USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",

  USER_LOG_IN_FAILURE: "USER_LOG_IN_FAILURE",
  USER_LOG_IN_SUCCESS: "USER_LOG_IN_SUCCESS",

  USER_FORGET_PASSWORD_FAILURE: "USER_FORGET_PASSWORD_FAILURE",
  USER_FORGET_PASSWORD_SUCCESS: "USER_FORGET_PASSWORD_SUCCESS",

  FORGET_PASSWORD_VERIFICATION_FAILURE: "FORGET_PASSWORD_VERIFICATION_FAILURE",
  FORGET_PASSWORD_VERIFICATION_SUCCESS: "FORGET_PASSWORD_VERIFICATION_SUCCESS",

  LOGOUT_ACTION: "LOGOUT_ACTION",

  RESET_ERROR: "RESET_ERROR",
};
