export const adminConstants = {
  AUTHENTICATION_FAILURE: "AUTHENTICATION_FAILURE",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",

  LOGOUT_ACTION: "LOGOUT_ACTION",

  RESET_ERROR: "RESET_ERROR",
};
